apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lightstreamer.fullname" . }}-conf
  labels:
    {{- include "lightstreamer.labels" . | nindent 4 }}
data:
  lightstreamer_conf.xml: |-
    {{- include "lightstreamer.configuration" . | nindent 4 }}
  lightstreamer_log_conf.xml: |-
    {{- include "lightstreamer.configuration.log" . | nindent 4 }}
  lightstreamer_edition_conf.xml: |-
    {{- include "lightstreamer.configuration.edition" . | nindent 4 }}  
  mime_types.properties: |-
    {{ .Files.Get "mime_types.properties" | nindent 4}}
