FROM lightstreamer

# Copy the adapter deployment files to the Lightstreamer adapters directory
COPY build/libs/example-adapter-set-1.0.0.jar /lightstreamer/adapters/example-adapter-set/lib/

# Copy the test page to the Lightstreamer pages directory
COPY index.html /lightstreamer/pages/index.html
