logging:
  loggers:
    lightstreamerLogger:

      # Set the logging level for Lightstreamer
      subLoggers:
        init: DEBUG

deployment:
  terminationGracePeriodSeconds: 2

adapters:

  # Define the adapter set
  exampleProxyAdapterSet:
    enabled: true
    id: EXAMPLE_PROXY_ADAPTER_SET

    # Define the metadata provider
    metadataProvider:

      # Define the In-Process Metadata Adapter
      inProcessMetadataAdapter:
        adapterClass: com.lightstreamer.adapters.metadata.LiteralBasedProvider

    dataProviders:

      # Define the data provider
      myDataProvider:
        enabled: true
        name: MY_PROXY_DATA_ADAPTER

        # Define the Proxy Data Adapter
        proxyDataAdapter:
          requestReplyPort: 6661

