logging:
  loggers:
    lightstreamerLogger:

      # Set the logging level for Lightstreamer
      subLoggers:
        init: DEBUG

deployment:
  terminationGracePeriodSeconds: 2

adapters:

  # Define the adapter set
  exampleAdapterSet:
    enabled: true
    id: EXAMPLE_ADAPTER_SET

    # Provision the adapter set from the image
    provisioning:
      fromPathInImage: /lightstreamer/adapters/example-adapter-set

    # Define the metadata provider
    metadataProvider:

      # Define the In-Process Metadata Adapter
      inProcessMetadataAdapter:
        adapterClass: com.lightstreamer.adapters.examples.meta.SimpleMetadataAdapter

    dataProviders:

      # Define the data provider
      myDataProvider:
        enabled: true
        name: MY_DATA_ADAPTER

        # Define the In-Process Data Adapter
        inProcessDataAdapter:
          adapterClass: com.lightstreamer.adapters.examples.data.SimpleDataAdapter

